In [5]:
#the following is the first notebook entry as i start to learn machine learning myself
#hopefully i can learn to do this and keep up a journal of my progress

In [6]:
import torch
torch.__version__

'2.0.1'

In [7]:
#scalar
scalar = torch.tensor(7)
#scalars are 0 dimensional tensors, they have no shape, no length, no dimension, no size
#they are created the same way as tensors, but with a single number, not a list
#the dimensions of a tensor a tensor start at 0 and then go to 1, 2, 3, etc 
#with a one dimensional tensor, you can think of it as a list of numbers like [1, 2, 3, 4, 5]
#for example torch.tensor([1, 2, 3, 4, 5]) is a one dimensional tensor with 5 elements
#and torch.tensor([1, 2, 3, 4, 5]).shape is torch.Size([5])
#whereas torch.tensor(7) is a 0 dimensional tensor with 1 element
#and torch.tensor([1],[2]) is a 2 dimensional tensor with 2 elements
#and torch.tensor([1],[2]).shape is torch.Size([2, 1])

In [8]:
scalar

tensor(7)

In [9]:
#to check the dimensions of a tensor (number of rows and columns)
scalar.ndim
#for clarity
print("scalar dimensions: ", scalar.ndim)

scalar dimensions:  0


In [10]:
#to get the number from the tensor
scalar.item()
#this will convert the value inside of the tensor to a python integer

7

In [11]:
#a vector is a single dimensional tensor that can have as many values as you want
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
#check the dimensions of the vector
vector.ndim

1

In [13]:
#the number of dimensions will match the number of brackets in the array
#([]) = 1D array (vector), ([[]]) = 2D array, ([[[ ]]]) = 3D array
#the shape of a tensor is how the elements inside the tensor is arranged
#this is how you check the shape
print("The shape of the tensor is: ", vector.shape)
#the size([2])means our vector has a shape of [2] this is because of the 2 elements in the vector
#([7,7])

The shape of the tensor is:  torch.Size([2])


In [14]:

#this is a matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
matrix.ndim
#its a 2D Tensor

2

In [16]:
matrix.shape
#the shape is 2 rows and 2 columns

torch.Size([2, 2])

In [17]:
#up until now they have all been gone over as tensors
#but its really like
#0D tensor = scalar, 1D tensor = vector, 2D tensor = matrix
#3D tensor = cube of numbers
#anything else would be a higher order tensor (4D, 5D, etc)
#like a hypercube

#this is a tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR
#tensors can represent almost anything
#the above tensor is a representation of sales numbers

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:

TENSOR.ndim

3

In [19]:
TENSOR.shape
#this is a bit confusing as it outputs ([1,3,3])
#but its a 3 dimenrsional tensor
#the dimensions go outter to inner


torch.Size([1, 3, 3])

In [21]:
"""
in conclusion, i have learned about the following:
scalar = single number and its dimension is 0
vector = a number with dirextion(like wind speed with direction) its dimension is 1
matrix = a 2d array of numbers its dimension is 2
tensor = a n-d array of numbers its dimension is n
"""
#ive learned i can use docstrings randomly for notes

'\nin conclusion, we have learned about the following:\nscalar = single number and its dimension is 0\nvector = a number with dirextion(like wind speed with direction) its dimension is 1\nmatrix = a 2d array of numbers its dimension is 2\ntensor = a n-d array of numbers its dimension is n\n'