# the following is the first notebook entry as i start to learn machine learning myself
## hopefully i can learn to do this and keep up a journal of my progress

In [49]:
import torch
torch.__version__

'2.0.0+cpu'

In [50]:
#scalar
scalar = torch.tensor(7)

scalars are 0 dimensional tensors, they have no shape, no length, no dimension, no size
they are created the same way as tensors, but with a single number, not a list
the dimensions of a tensor a tensor start at 0 and then go to 1, 2, 3, etc 
with a one dimensional tensor, you can think of it as a list of numbers like [1, 2, 3, 4, 5]
for example torch.tensor([1, 2, 3, 4, 5]) is a one dimensional tensor with 5 elements
and torch.tensor([1, 2, 3, 4, 5]).shape is torch.Size([5])
whereas torch.tensor(7) is a 0 dimensional tensor with 1 element
and torch.tensor([1],[2]) is a 2 dimensional tensor with 2 elements
and torch.tensor([1],[2]).shape is torch.Size([2, 1])

In [51]:
scalar

tensor(7)

In [52]:
#to check the dimensions of a tensor (number of rows and columns)
scalar.ndim
#for clarity
print("scalar dimensions: ", scalar.ndim)

scalar dimensions:  0


In [53]:
#to get the number from the tensor
scalar.item()
#this will convert the value inside of the tensor to a python integer

7

In [54]:
#a vector is a single dimensional tensor that can have as many values as you want
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [55]:
#check the dimensions of the vector
vector.ndim

1

the number of dimensions will match the number of brackets in the array
([]) = 1D array (vector), ([[]]) = 2D array, ([[[ ]]]) = 3D array
the shape of a tensor is how the elements inside the tensor is arranged

In [56]:
#this is how you check the shape
print("The shape of the tensor is: ", vector.shape)
#the size([2])means our vector has a shape of [2] this is because of the 2 elements in the vector
#([7,7])

The shape of the tensor is:  torch.Size([2])


In [57]:

#this is a matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [58]:
matrix.ndim
#its a 2D Tensor

2

In [59]:
matrix.shape
#the shape is 2 rows and 2 columns

torch.Size([2, 2])

up until now they have all been gone over as tensors
but its really like
0D tensor = scalar, 1D tensor = vector, 2D tensor = matrix
3D tensor = cube of numbers
anything else would be a higher order tensor (4D, 5D, etc)
like a hypercube

In [60]:
#this is a tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR
#tensors can represent almost anything
#the above tensor is a representation of sales numbers

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [61]:

TENSOR.ndim

3

In [62]:
TENSOR.shape
#this is a bit confusing as it outputs ([1,3,3])
#but its a 3 dimenrsional tensor
#the dimensions go outter to inner


torch.Size([1, 3, 3])

In [63]:
"""
in conclusion, i have learned about the following:
scalar = single number and its dimension is 0
vector = a number with dirextion(like wind speed with direction) its dimension is 1
matrix = a 2d array of numbers its dimension is 2
tensor = a n-d array of numbers its dimension is n
"""
#ive learned i can use docstrings randomly for notes

'\nin conclusion, i have learned about the following:\nscalar = single number and its dimension is 0\nvector = a number with dirextion(like wind speed with direction) its dimension is 1\nmatrix = a 2d array of numbers its dimension is 2\ntensor = a n-d array of numbers its dimension is n\n'

In [64]:
#to create a tensor of random numbers
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.ndim, random_tensor.shape

(tensor([[0.8437, 0.4264, 0.2244, 0.0919],
         [0.4324, 0.7299, 0.6532, 0.8335],
         [0.2882, 0.0357, 0.0098, 0.3863]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

In [65]:
#this can be used to make random tensors in whatever size you want
#for example you could use torch.random(244,244,3)
#this wuold follow the common shape of an image
random_image_size_tensor = torch.rand(size=(244,244,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim



(torch.Size([244, 244, 3]), 3)

- hey copilot do i need to specify the size = key?
- copilot: no, you can just do torch.rand((244,244,3))
- why the double parenthesis?
- copilot: because it's a tuple
- so rand takes a tuple as an argument?
- copilot: yes
- will rand(244,244,3) work?
- copilot: no, it will throw an error

In [66]:
#to create a tensor full of zeros
zeros = torch.zeros(3,4)
zeros, zeros.dtype
#this can be used to create a tensor of any shape
#and the zeros can be accessed and filled with values

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [67]:
#to create a tensor full of ones
ones = torch.ones(3,4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [68]:
#to create a range of values
zero_to_ten = torch.arange(start=0, end=10, step=1)

zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

this is the pytorch arange (not arrange) function
it is used to create a range of values with a set interval
the start is the first value in the range
the end is the last value in the range
the step is the interval between each value in the range
its important to remember it returns a tensor

- hey copilot is like everything in torch just about tensors?
- copilot: yes, tensors are the main data structure in torch
- copilot: tensors are like numpy arrays, but they can also be used on a GPU to accelerate computing
- copilot: tensors are also optimized for automatic differentiation
- copilot: tensors are also the main data structure for neural networks in pytorch
- thanks copilot
- copilot: no problem
- copilot: I'm here to help
- is shape a very important thing in torch?
- copilot: yes, shape is very important in torch
- so in the same way that i would need torch.zeros and torch.ones
to create a tensor of zeros and ones of any size from the jump
i would need torch.zeros_like and torch.ones_like
to create a tensor of ones or zeros in the same shape
as some other data im working with?
- copilot: yes, that's correct

In [69]:

#to create a tensor of zeros or ones in the same shape as some other data
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

- copilot why are there so many data types in pytorch?
- copilot: because it's a dynamic language
- copilot: and it's a language that's designed to be used in a dynamic way
- is it bc some of the data types are for the gpu and some are for the cpu
- copilot: no, it's because some of the data types are for the gpu and some are for the cpu
- that is literally what i asked you
- copilot: i'm not sure what you mean by that
- -.-
- what is the most common data type?
- copilot: the most common data type is the float
- so like a float32?
- copilot: yes
- what is the difference between a float and a float32?
- copilot: a float is a floating point number, and a float32 is a floating point number with 32 bits
- to create a tensor with a specific datatype

In [70]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #the default arg is none, which is automatically a float32
                               device=None, #the default arg is none, which is automatically a cpu
                               requires_grad=False) #the default arg is false, which means that the tensor will not be used in a gradient computation, if true then operations on the tensor will be recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.requires_grad

(torch.Size([3]), torch.float32, device(type='cpu'), False)

In [71]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) #torch.half would also work

float_16_tensor.dtype

torch.float16

In [72]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f'shape of some_tensor: {some_tensor.shape}')
print(f'dtype of some_tensor: {some_tensor.dtype}')
print(f'device of some_tensor: {some_tensor.device}')


tensor([[0.4767, 0.0268, 0.7756, 0.1756],
        [0.0338, 0.4729, 0.4134, 0.6030],
        [0.1547, 0.5538, 0.3529, 0.2361]])
shape of some_tensor: torch.Size([3, 4])
dtype of some_tensor: torch.float32
device of some_tensor: cpu


In [73]:
#math works on tensors
#to create a tensor and add to it
tensor = torch.tensor([1,2,3])
tensor, tensor + 10
#this will add 10 to each element in the tensor

(tensor([1, 2, 3]), tensor([11, 12, 13]))

In [74]:
#to multiply
tensor * 10
#this will multiply each element by 10

tensor([10, 20, 30])

In [75]:
#tensors dont change until they have been reassigned
tensor

tensor([1, 2, 3])

In [76]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [77]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [78]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [79]:
tensor

tensor([1, 2, 3])

In [80]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [81]:
#testing matrix multplication
tensor = torch.tensor([1,2,3]) #one dimensional tensor, or vector wirh a shape of [3]
tensor.shape, tensor.ndim

(torch.Size([3]), 1)

the difference between elemeent wise multiplication
and matrix multiplication is the addition of value
for tensor i can think about element wise multiplication as
[1*1, 2*2, 3*3] = [1,4,9] tensor * tensor
and then i can think of a matrix multiplication as [1*1, 2*2, 3*3] = [14]
tensor.matmula(tensor)

In [82]:
#elementwise, matmulwise
tensor * tensor, torch.matmul(tensor, tensor)
#this will be useful to quickly do math even graphics like rotating an ascii cube

(tensor([1, 4, 9]), tensor(14))

In [83]:
#its either in python itself or pytorch that the @ 
#is the symbol for matrix multiplicaion
tensor @ tensor, tensor @ torch.tensor([1,3,4])

(tensor(14), tensor(19))

in the past algo has told me not to waste time with writing my own matrix multiplication functions
this is not to ignore that but to at least know whats under the hood so im not blindly using

In [84]:
#by hand implementation
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

tensor(14)

In [85]:
#this is obviously much faster
torch.matmul(tensor, tensor)

tensor(14)

In [86]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

this didnt seem obvious to me at first and now i understand
what algo and chris meant by touch the tensor and see the shape
its becoming clear i coulndt progress without proper pytorch knowlege

at first to the eye intuitively these look like something should be able
to be done with them and there prolly is but its not what i am trying to
do with them right now, the shape is identical, and thats the issue
in the case of matrix multiplication the shape has to have the same inner
multiplacitively speaking, so [3,2] @ [3,2] wont work but
[anything, 2] @ [2, anything] would and if there are errors like this
in the future i can just touch the tensor

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

linear algebra is supposed to be important in machine learning
torch is a library for linear algebra
torch is a library for tensor computation
tensor is a generalization of vectors and matrices
a liner linear function can be accurately represented (i think) 
as **y = x * A^T + b**
where x is the input to the layer,
A is the weight matrix, created by the layer, it starts out as random
numbers that get adjusted as neural networks lean to better represent
patterns in the data
T is the transpose of A, because the matrix of weights gets transposed
b is the bias vector, created by the layer, it starts out as random
y is the output of the layer
if this is inaccurate dont sue me im wingin this


In [ ]:

#trying out a linear layer
#since it starts as a random weight matrix, i can make it reproduceable wtih a seed
torch.manual_seed(42)
#this uses matrix multiplication
linear = torch.nn.Linear(in_features=2, #in_features is the number of inputs
                         out_features=6)  #out_features is the number of outputs, it describes outter values
x = tensor_A
output = linear(x)
print(f"input shape: {x.shape}\n")
print(f"output:\n{output}\n\nOutput shape: {output.shape}")


input shape: torch.Size([2, 3])

output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])


if i were to change the in_features to 3, it would throw an error
because the input is a 2d tensor, and the in_features is 3
it can be fixed with a transpose

In [ ]:
#create a tensor
x = torch.arange(0, 100, 10) #dont forget that arange is arange(start, end, step)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"minimum:{x.min()}, maximum:{x.max()}")
# print(F'mean:{x.mean()}) #this will error
print(f'mean:{x.type(torch.float32).mean()}') #this operation wont work if i just do {x.mean()}
print(f'sum:{x.sum()}')

minimum:0, maximum:90
mean:45.0
sum:450


In [ ]:
#the follwing will work the same as above
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [ ]:
#to learn indexing i have to create a new tensor
tensor = torch.arange(10,100,10)
print(tensor)
print(f'index where max value is {tensor.argmax()}')
print(f'index where min value is {tensor.argmin()}')

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
index where max value is 8
index where min value is 0


In [ ]:
#create a new tensor(prolly gonna do this a ton)
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [ ]:
#create a float 16 tensor
tensorfloat16 = tensor.type(torch.float16) #type will create a copy of the tensor fed to it through it and convert it to the type specified
tensorfloat16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensorint8 = tensor16.type(torch.int8)
tensorint8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [ ]:
#create a tensor
x = torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
#im going to try adding dimension with reshape()
x_reshape = x.reshape(1,7)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
#another way to change the shape of a tensor is to use .view() method
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

### quick ref will return to later
Assume x is a 2-dimensional tensor (or a matrix). Here are some ways you can index into x:
Select a specific element: x[i, j] will select the element at the i-th row and j-th column.
Select a specific row or column: x[i, :] will select the i-th row, and x[:, j] will select the j-th column.
Select multiple rows or columns: x[1:3, :] will select rows 1 and 2 (note that the end index is exclusive), 
and x[:, 1:3] will select columns 1 and 2.
Select with a step: x[::2, :] will select every other row, starting from row 0.
Select with negative indices: x[-1, :] will select the last row. Negative indices count from the end.
Use boolean indexing: If you have a tensor of the same shape as x, but with boolean values (i.e., True and False),
you can use this as an index. x[boolean_tensor] will select all elements of x where the corresponding value in the boolean tensor is True.
Use integer indexing: You can create a tensor of integers to select multiple rows or columns in a specific order or multiple times.
x[[1, 2, 1], :] will select the second, third, and second rows of x.

In [ ]:

z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [88]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) #stack is used to stack tensors on top of each other, which adds a new dimension
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [89]:
#to remove all single dimensions from a tensor use torch.squeeze()
print(f'previous tensor:{x_reshape}')
print(f'previous shape:{x_reshape.shape}')
x_squeezed = torch.squeeze(x_reshape) #torch.squeeze() removes all single dimensions from a tensor in other words it removes anythihng that has a size of 1
print(f'new tensor:{x_squeezed}')
print(f'new shape:{x_squeezed.shape}')
#youre squeezing the tensor to only have dimensions over 1, or squeezing out all the 1s

previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7.]])
previous shape:torch.Size([1, 7])
new tensor:tensor([5., 2., 3., 4., 5., 6., 7.])
new shape:torch.Size([7])


In [94]:
print(x_squeezed)
xunsqueezed = x_squeezed.unsqueeze(dim=0) #this adds a dimension to a specific index
print(xunsqueezed)


tensor([5., 2., 3., 4., 5., 6., 7.])
tensor([[5., 2., 3., 4., 5., 6., 7.]])


i can also rearrange the order of axes values with permute(input, dims)
where input gets turned into a view with new dims

In [97]:

#create a tensor with a specific shape
x_og = torch.rand(size=(244,244,3))

#permute the og tensor to rearrange the axis order
x_perm = x_og.permute(2,0,1)

print(x_og)

torch.Size([244, 244, 3])


In [ ]:
 .-._                                                   _,-,
  `._`-._                                           _,-'_,'
     `._ `-._                                   _,-' _,'
        `._  `-._        __.-----.__        _,-'  _,'
           `._   `#==="""           """===#'   _,'
              `._/)  ._               _.  (\_,'
               )*'     **.__     __.**     '*( 
               #  .==..__  ""   ""  __..==,  # 
BOO            #   `"._(_).       .(_)_."'   #

# indexing(selecting data from tensors)
to select specific data from tensors(like only the first column or second row)
to do so i can index like in vanilla python or numpy

In [3]:
#create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

indexing the values of a tensor goes: outer dimension -> inner dimension (check brackets)

In [4]:
#indexing bracket by bracket
print(f'first square bracket\n{x[0]}')
print(f'second square bracket\n{x[0][0]}')
print(f'third square bracket\n{x[0][0][0]}')


first square bracket
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
second square bracket
tensor([1, 2, 3])
third square bracket
1


on god for real for real, i feel like this is probnobably going to be the most im[port]ant thing i have written so far. it seems like all of the
cool stuff ive seen algo do is like really sick indexing, the idea of saying "really sick indexing" is making me wanna **play sudoku**

i can also use : to specify "all values in this dimension" and then use a comma to add another dimension

In [5]:
#get all values of the 0th dimension and the 0 index of the 1st dimension
print(x[:,0])

tensor([[1, 2, 3]])


In [6]:
#get all the values of the 0th and 1st dimensions but only the index 1 of the 2nd dimension
print(x[:, :, 1])

tensor([[2, 5, 8]])


In [7]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [8]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

since numpy is so popular pytorch is made to interface with it well
two main methods to make early note of are:
- torch.from_numpy(ndarray) - numpy array to pytorch tensor
- torch.Tensor.numpy() - pytorch tensor to numpy array

In [9]:
#numpy to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

by default numpy arrays are created with the datatype float64 and if you convert it to a pytorch tensor it will keep the same datatype.
however because so many tensors are float32 i can convert the array with type after its been made into a tensor 

In [10]:
#change array keep tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [13]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [14]:
#change tensor keep the array
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

reproducability is important in machine learning and data science so i need to learn how to use randomness in a reproducable way
start with random #'s => tensor operations => improve 

In [15]:
#create two random tensors
randa = torch.rand(3,4)
randb = torch.rand(3,4)

print(f'tensor a: {randa}\n')
print(f'tensor b: {randb}\n')
print(f'does tensor a = tensor b anywhere?')
randa == randb

tensor a: tensor([[0.4691, 0.2155, 0.8268, 0.4587],
        [0.9260, 0.5322, 0.4424, 0.4334],
        [0.4530, 0.5870, 0.2849, 0.6589]])

tensor b: tensor([[0.8266, 0.3321, 0.5549, 0.6163],
        [0.4418, 0.5237, 0.4263, 0.6685],
        [0.7419, 0.2461, 0.5976, 0.6359]])

does tensor a = tensor b anywhere?


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

these are different even though they both look identical because they are random from a different seed
i can use torch.manual_seed(seed) to set the seed to the same place every time so the sensation of random is aligned in that instance

In [16]:
import random

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
randomtensor = torch.rand(3, 4)
                                    # its important to set the seed before creating the tensor each time
torch.manual_seed(RANDOM_SEED)
randomtensor2 = torch.rand(3, 4)

print(f'randomtensor: {randomtensor}')
print(f'randomtensor2: {randomtensor2}')
print(f'does randomtensor == randomtensor2? {randomtensor == randomtensor2}')

randomtensor: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
randomtensor2: tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
does randomtensor == randomtensor2? tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [17]:
"""⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣤⣤⣤⣤⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ you can do all of this stuff on cpu or gpu if you have one⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⠿⠋⠉⠁⠀⠀⠀⠹⢿⡿⣿⡻⠟⠿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⡿⡃⠀⠀⠀⠀⠀⠀⠀⠰⡄⢹⣿⡇⠀⢻⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣻⠁⠀⠀⠀⠀⠀⠀⠀⠀⣛⣼⡿⠃⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣶⣿⣿⣷⣶⣦⣤⣀⡀⠀⠀                  running tensors on gpus
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⡇⠻⣿⣤⣀⠀⠀⢀⣠⣤⡶⠟⠛⠁⠀⠀⠀⠈⠙⠓⠲⠶⠦⣤⣤⣄⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⠟⠋⢙⣿⣿⣿⣿⣿⣿⣿⣿⣶⣄               lets the computer do all the
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣿⣦⠈⠉⠛⠛⠛⠋⠉⠀⠀⢀⣀⣀⣀⣠⣤⣤⣤⣤⣤⣤⣀⣀⣀⣀⠈⠉⠙⠓⠲⠶⢤⣀⡀⠀⠀⠀⡏⠀⢠⣾⠋⠁⠛⣉⡈⠙⠻⢿⣿⣿              calculations way more better
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⣿⠇⠀⢀⣀⣴⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣦⣄⣀⠀⠉⠉⠛⠛⠃⠀⠀⣿⡄⠀⠀⠀⠀⠀⠀⠀⠙⢿               so that everything is done
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡾⢃⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⣄⡀⠀⠀⠀⠉⢷⣄⠀⠀⠀⠀⠀⠀⠀⢠               faster and more efficient
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣯⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⡀⠀⠀⠙⢷⣄⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⠟⠋⠉⠉⠉⠉⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⠀⠀⠙⠳⣤⣀⠀⠀⣐
⠀⠀⠀⠀⠀⠀⠀⠀⣰⢟⣿⣿⣿⣿⣿⣿⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠈⠉⠛⠛⠉
⠀⠀⠀⠀⠀⠀⠀⣼⢏⣾⣿⣿⣿⣿⣿⡟⠛⠛⣶⣄⣀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀⠀⢈⣼⡿
⠀⠀⠀⠀⠀⠀⣸⠏⣾⣿⣿⣿⣿⣿⣿⠀⠀⢰⡏⠉⠙⠻⠷⣶⣤⣄⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠋⠉⠛⠻⣿⣿⣿⣿⣿⣄⠀⢿⠁⠀
⠀⠀⠀⠀⠀⣴⡏⣸⣿⣿⣿⣿⣿⣿⡏⠀⠀⢸⡇⠀⠀⠀⣠⡿⠃⠈⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⠀⠀⠀⠀⠀⠀⠈⢻⣿⣿⣿⣿⣆⠸⣇⠀
⠀⠀⠀⠀⣰⡟⢰⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠘⢷⣤⣤⠾⠋⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⡆⢹⡀
⠀⠀⠀⣰⣿⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⣀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠷⠤⣤⣤⣤⣤⣤⣤⣤⣀⣀⣸⣿⣿⣿⣿⣷⡈⢧
⠀⠀⠀⣿⡇⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣤⣤⣤⣴⣶⣿⣿⣿⣿⣿⣿⣿⠿⠿⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⢹⡆⠀⠀⠀⢈⣽⠃⠀⢹⣿⣿⣿⣿⣿⡇⠈
⠀⠀⠀⣿⡇⠀⠈⢿⣿⣿⣿⣿⠿⠿⢿⣽⡟⣿⣿⣿⣿⣿⣿⡿⠟⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠻⢿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠈⢷⡄⢀⣠⡿⠁⠀⢀⣿⣿⣿⣿⣿⣿⡇⠀                 
⠀⠀⠀⣿⢑⣂⣠⣤⣿⣿⡷⢶⣶⣶⠀⠙⣿⢻⣿⡿⠟⠉⠁⠀⠀⠀⠀⢀⣤⣴⣶⣶⣶⣦⣤⣀⠀⠀⠀⠈⠛⢿⣿⣿⣿⣿⣧⠀⠀⠀⠙⠛⠉⠀⠀⢀⣼⣿⣿⣿⣿⣿⣿⡇⠀
⠀⠀⠀⣿⣾⣿⣿⣏⠀⠀⠀⠀⠀⠀⢀⣼⠋⢸⡇⠀⠀⠀⠀⠀⠀⠀⣤⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⡄⠀⠀⠀⠙⢿⣿⣿⣿⣷⣤⡀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⠇⠀
⠀⢀⣠⣿⣿⣿⡿⠿⠿⠀⠀⠀⢀⣴⡿⠁⠀⣾⡇⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠹⢿⣿⣿⣿⣿⣿⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀
⣾⣿⣿⣿⣟⣿⣿⣷⣄⠀⢀⣴⣿⠟⠀⢀⣼⢟⣿⣀⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀
⣿⣿⢛⣻⣝⡟⢿⣟⢿⣷⣨⡿⠃⠀⢠⣿⡋⢸⣿⠛⠻⢶⣄⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠒⠀⠀⠀⠀⠀⠀⠀⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀
⡿⣽⣿⣿⣿⣿⣆⢻⡏⣿⡏⠀⠀⢀⣾⢋⣷⣾⣿⣦⡀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠿⣿⣿⣿⣿⣿⣿⣿⠟⠃⠀⠀⠀⣸
⡵⣿⣿⣿⣿⣿⣿⠄⣿⣿⡇⠀⣶⣿⣿⣸⣿⣿⣿⣿⣿⡆⠀⠀⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡇
⣧⡻⣿⣿⣿⣿⠟⣼⡏⣿⠇⠜⣰⣏⣿⣿⣿⣿⣿⣿⡏⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡿⠀
⠈⠻⣦⣤⣤⣤⠞⢙⣹⡿⠀⣰⡿⠛⠿⢿⣿⣿⣿⡿⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡿⠁⠀
⠀⠀⣠⣬⣭⡀⠀⢿⡏⠀⣴⣯⠁⠀⠒⠒⢾⣿⣿⡇⠀⣀⣀⡀⢠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⣤⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣤⣾⠟⠃⠀⠀
⣤⣿⣿⣿⣷⣔⣖⣼⠀⣰⣿⢹⢀⣄⠀⠀⢸⣽⣿⡇⠀⠀⠀⢨⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣶⣶⣶⣶⣿⣿⣿⠟⠋⠁⠀⠀⠀⠀
⢿⠸⣿⣿⣿⡿⣽⡿⣰⣿⢃⣿⠮⣽⣶⣴⡿⠿⠟⢧⡀⠀⠀⣿⠋⠉⠉⠙⠛⠛⠿⠿⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠋⠀⠀⠀⠀⠀⠀⠀⠀
⣧⡷⣌⣉⣉⣥⣿⣵⡏⣤⣿⠇⠀⠀⠀⠀⠀⠀⠀⠈⢿⡷⠾⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠳⠦⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣿⣿⣶⣤⣤⣴⣿⣿⡿⠛⠁⠀⠀⠀⠀⠀⠀⠀⣀⢀⣋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠶⢤⣤⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀""" #give me a gpu or else (i will cry)

'⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣤⣤⣤⣤⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ you can do all of this stuff on cpu or gpu if you have one⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⠿⠋⠉⠁⠀⠀⠀⠹⢿⡿⣿⡻⠟⠿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⡿⡃⠀⠀⠀⠀⠀⠀⠀⠰⡄⢹⣿⡇⠀⢻⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣻⠁⠀⠀⠀⠀⠀⠀⠀⠀⣛⣼⡿⠃⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣶⣿⣿⣷⣶⣦⣤⣀⡀⠀⠀                  running tensors on gpus\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⡇⠻⣿⣤⣀⠀⠀⢀⣠⣤⡶⠟⠛⠁⠀⠀⠀⠈⠙⠓⠲⠶⠦⣤⣤⣄⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⠟⠋⢙⣿⣿⣿⣿⣿⣿⣿⣿⣶⣄               lets the computer do all the\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣿⣦⠈⠉⠛⠛⠛⠋⠉⠀⠀⢀⣀⣀⣀⣠⣤⣤⣤⣤⣤⣤⣀⣀⣀⣀⠈⠉⠙⠓⠲⠶⢤⣀⡀⠀⠀⠀⡏⠀⢠⣾⠋⠁⠛⣉⡈⠙⠻⢿⣿⣿              calculations way more better\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⣿⠇⠀⢀⣀⣴⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣦⣄⣀⠀⠉⠉⠛⠛⠃⠀⠀⣿⡄⠀⠀⠀⠀⠀⠀⠀⠙⢿               so that everything is done\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡾⢃⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⣄⡀⠀⠀⠀⠉⢷⣄⠀⠀⠀⠀⠀⠀⠀⢠               faster and more efficient\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣯⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⡀⠀⠀⠙⢷⣄⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⠟⠋⠉⠉⠉⠉⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⠀⠀⠙⠳⣤⣀⠀