In [2]:
#the following is the first notebook entry as i start to learn machine learning myself
#hopefully i can learn to do this and keep up a journal of my progress

In [3]:
import torch
torch.__version__

'2.0.1'

In [4]:
#scalar
scalar = torch.tensor(7)
#scalars are 0 dimensional tensors, they have no shape, no length, no dimension, no size
#they are created the same way as tensors, but with a single number, not a list
#the dimensions of a tensor a tensor start at 0 and then go to 1, 2, 3, etc 
#with a one dimensional tensor, you can think of it as a list of numbers like [1, 2, 3, 4, 5]
#for example torch.tensor([1, 2, 3, 4, 5]) is a one dimensional tensor with 5 elements
#and torch.tensor([1, 2, 3, 4, 5]).shape is torch.Size([5])
#whereas torch.tensor(7) is a 0 dimensional tensor with 1 element
#and torch.tensor([1],[2]) is a 2 dimensional tensor with 2 elements
#and torch.tensor([1],[2]).shape is torch.Size([2, 1])

In [5]:
scalar

tensor(7)

In [6]:
#to check the dimensions of a tensor (number of rows and columns)
scalar.ndim
#for clarity
print("scalar dimensions: ", scalar.ndim)

scalar dimensions:  0


In [7]:
#to get the number from the tensor
scalar.item()
#this will convert the value inside of the tensor to a python integer

7

In [8]:
#a vector is a single dimensional tensor that can have as many values as you want
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
#check the dimensions of the vector
vector.ndim

1

In [10]:
#the number of dimensions will match the number of brackets in the array
#([]) = 1D array (vector), ([[]]) = 2D array, ([[[ ]]]) = 3D array
#the shape of a tensor is how the elements inside the tensor is arranged
#this is how you check the shape
print("The shape of the tensor is: ", vector.shape)
#the size([2])means our vector has a shape of [2] this is because of the 2 elements in the vector
#([7,7])

The shape of the tensor is:  torch.Size([2])


In [11]:

#this is a matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim
#its a 2D Tensor

2

In [13]:
matrix.shape
#the shape is 2 rows and 2 columns

torch.Size([2, 2])

In [14]:
#up until now they have all been gone over as tensors
#but its really like
#0D tensor = scalar, 1D tensor = vector, 2D tensor = matrix
#3D tensor = cube of numbers
#anything else would be a higher order tensor (4D, 5D, etc)
#like a hypercube

#this is a tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR
#tensors can represent almost anything
#the above tensor is a representation of sales numbers

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:

TENSOR.ndim

3

In [16]:
TENSOR.shape
#this is a bit confusing as it outputs ([1,3,3])
#but its a 3 dimenrsional tensor
#the dimensions go outter to inner


torch.Size([1, 3, 3])

In [17]:
"""
in conclusion, i have learned about the following:
scalar = single number and its dimension is 0
vector = a number with dirextion(like wind speed with direction) its dimension is 1
matrix = a 2d array of numbers its dimension is 2
tensor = a n-d array of numbers its dimension is n
"""
#ive learned i can use docstrings randomly for notes

'\nin conclusion, i have learned about the following:\nscalar = single number and its dimension is 0\nvector = a number with dirextion(like wind speed with direction) its dimension is 1\nmatrix = a 2d array of numbers its dimension is 2\ntensor = a n-d array of numbers its dimension is n\n'

In [18]:
#to create a tensor of random numbers
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.ndim, random_tensor.shape

(tensor([[0.3773, 0.3884, 0.4014, 0.1969],
         [0.5108, 0.9586, 0.3679, 0.0583],
         [0.2928, 0.8719, 0.9060, 0.2411]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

In [19]:
#this can be used to make random tensors in whatever size you want
#for example you could use torch.random(244,244,3)
#this wuold follow the common shape of an image
random_image_size_tensor = torch.rand(size=(244,244,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim
#hey copilot do i need to specify the size = key?
#copilot: no, you can just do torch.rand((244,244,3))
#why the double parenthesis?
#copilot: because it's a tuple
#so rand takes a tuple as an argument?
#copilot: yes
#will rand(244,244,3) work?
#copilot: no, it will throw an error


(torch.Size([244, 244, 3]), 3)

In [20]:
#to create a tensor full of zeros
zeros = torch.zeros(3,4)
zeros, zeros.dtype
#this can be used to create a tensor of any shape
#and the zeros can be accessed and filled with values

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [21]:
#to create a tensor full of ones
ones = torch.ones(3,4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [22]:
#to create a range of values
zero_to_ten = torch.arange(start=0, end=10, step=1)
#this is the pytorch arange (not arrange) function
#it is used to create a range of values with a set interval
#the start is the first value in the range
#the end is the last value in the range
#the step is the interval between each value in the range
#its important to remember it returns a tensor
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#hey copilot is like everything in torch just about tensors?
#copilot: yes, tensors are the main data structure in torch
#copilot: tensors are like numpy arrays, but they can also be used on a GPU to accelerate computing
#copilot: tensors are also optimized for automatic differentiation
#copilot: tensors are also the main data structure for neural networks in pytorch
#thanks copilot
#copilot: no problem
#copilot: I'm here to help
#is shape a very important thing in torch?
#copilot: yes, shape is very important in torch
"""so in the same way that i would need torch.zeros and torch.ones
to create a tensor of zeros and ones of any size from the jump
i would need torch.zeros_like and torch.ones_like
to create a tensor of ones or zeros in the same shape
as some other data im working with?"""
#copilot: yes, that's correct
#to create a tensor of zeros or ones in the same shape as some other data
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
#copilot why are there so many data types in pytorch?
#copilot: because it's a dynamic language
#copilot: and it's a language that's designed to be used in a dynamic way
#is it bc some of the data types are for the gpu and some are for the cpu
#copilot: no, it's because some of the data types are for the gpu and some are for the cpu
#that is literally what i asked you
#copilot: i'm not sure what you mean by that
#-.-
#what is the most common data type?
#copilot: the most common data type is the float
#so like a float32?
#copilot: yes
#what is the difference between a float and a float32?
#copilot: a float is a floating point number, and a float32 is a floating point number with 32 bits
#to create a tensor with a specific datatype
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #the default arg is none, which is automatically a float32
                               device=None, #the default arg is none, which is automatically a cpu
                               requires_grad=False) #the default arg is false, which means that the tensor will not be used in a gradient computation, if true then operations on the tensor will be recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.requires_grad

(torch.Size([3]), torch.float32, device(type='cpu'), False)

In [25]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) #torch.half would also work

float_16_tensor.dtype

torch.float16

In [26]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f'shape of some_tensor: {some_tensor.shape}')
print(f'dtype of some_tensor: {some_tensor.dtype}')
print(f'device of some_tensor: {some_tensor.device}')


tensor([[0.9704, 0.4741, 0.4316, 0.3457],
        [0.1010, 0.3938, 0.8459, 0.4510],
        [0.5559, 0.8063, 0.6979, 0.7721]])
shape of some_tensor: torch.Size([3, 4])
dtype of some_tensor: torch.float32
device of some_tensor: cpu


In [27]:
#math works on tensors
#to create a tensor and add to it
tensor = torch.tensor([1,2,3])
tensor, tensor + 10
#this will add 10 to each element in the tensor

(tensor([1, 2, 3]), tensor([11, 12, 13]))

In [28]:
#to multiply
tensor * 10
#this will multiply each element by 10

tensor([10, 20, 30])

In [29]:
#tensors dont change until they have been reassigned
tensor

tensor([1, 2, 3])

In [30]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [31]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [32]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [33]:
tensor

tensor([1, 2, 3])

In [34]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [35]:
#testing matrix multplication
tensor = torch.tensor([1,2,3]) #one dimensional tensor, or vector wirh a shape of [3]
tensor.shape, tensor.ndim

(torch.Size([3]), 1)

In [36]:
"""the difference between elemeent wise multiplication
and matrix multiplication is the addition of value
for tensor i can think about element wise multiplication as
[1*1, 2*2, 3*3] = [1,4,9] tensor * tensor
and then i can think of a matrix multiplication as [1*1, 2*2, 3*3] = [14]
tensor.matmula(tensor)"""

#elementwise, matmulwise
tensor * tensor, torch.matmul(tensor, tensor)
#this will be useful to quickly do math even graphics like rotating an ascii cube


(tensor([1, 4, 9]), tensor(14))

In [37]:
#its either in python itself or pytorch that the @ 
#is the symbol for matrix multiplicaion
tensor @ tensor, tensor @ torch.tensor([1,3,4])

(tensor(14), tensor(19))

In [38]:
#in the past algo has told me not to waste time with writing my own matrix multiplication functions
#this is not to ignore that but to at least know whats under the hood so im not blindly using
#by hand implementation
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

tensor(14)

In [39]:
#this is obviously much faster
torch.matmul(tensor, tensor)

tensor(14)

In [40]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape
"""
this didnt seem obvious to me at first and now i understand
what algo and chris meant by touch the tensor and see the shape
its becoming clear i coulndt progress without proper pytorch knowlege

at first to the eye intuitively these look like something should be able
to be done with them and there prolly is but its not what i am trying to
do with them right now, the shape is identical, and thats the issue
in the case of matrix multiplication the shape has to have the same inner
multiplacitively speaking, so [3,2] @ [3,2] wont work but
[anything, 2] @ [2, anything] would and if there are errors like this
in the future i can just touch the tensor
"""


(torch.Size([3, 2]), torch.Size([3, 2]))

In [41]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [42]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [43]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [44]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
#linear algebra is supposed to be important in machine learning
#torch is a library for linear algebra
#torch is a library for tensor computation
#tensor is a generalization of vectors and matrices
"""a liner linear function can be accurately represented (i think) 
as y = x * A^T + b
where x is the input to the layer,
A is the weight matrix, created by the layer, it starts out as random
numbers that get adjusted as neural networks lean to better represent
patterns in the data
T is the transpose of A, because the matrix of weights gets transposed
b is the bias vector, created by the layer, it starts out as random
y is the output of the layer
if this is inaccurate dont sue me im wingin this
"""
