In [2]:
#the following is the first notebook entry as i start to learn machine learning myself
#hopefully i can learn to do this and keep up a journal of my progress

In [3]:
import torch
torch.__version__

'2.0.1'

In [4]:
#scalar
scalar = torch.tensor(7)
#scalars are 0 dimensional tensors, they have no shape, no length, no dimension, no size
#they are created the same way as tensors, but with a single number, not a list
#the dimensions of a tensor a tensor start at 0 and then go to 1, 2, 3, etc 
#with a one dimensional tensor, you can think of it as a list of numbers like [1, 2, 3, 4, 5]
#for example torch.tensor([1, 2, 3, 4, 5]) is a one dimensional tensor with 5 elements
#and torch.tensor([1, 2, 3, 4, 5]).shape is torch.Size([5])
#whereas torch.tensor(7) is a 0 dimensional tensor with 1 element
#and torch.tensor([1],[2]) is a 2 dimensional tensor with 2 elements
#and torch.tensor([1],[2]).shape is torch.Size([2, 1])

In [5]:
scalar

tensor(7)

In [6]:
#to check the dimensions of a tensor (number of rows and columns)
scalar.ndim
#for clarity
print("scalar dimensions: ", scalar.ndim)

scalar dimensions:  0


In [7]:
#to get the number from the tensor
scalar.item()
#this will convert the value inside of the tensor to a python integer

7

In [8]:
#a vector is a single dimensional tensor that can have as many values as you want
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
#check the dimensions of the vector
vector.ndim

1

In [10]:
#the number of dimensions will match the number of brackets in the array
#([]) = 1D array (vector), ([[]]) = 2D array, ([[[ ]]]) = 3D array
#the shape of a tensor is how the elements inside the tensor is arranged
#this is how you check the shape
print("The shape of the tensor is: ", vector.shape)
#the size([2])means our vector has a shape of [2] this is because of the 2 elements in the vector
#([7,7])

The shape of the tensor is:  torch.Size([2])


In [11]:

#this is a matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim
#its a 2D Tensor

2

In [13]:
matrix.shape
#the shape is 2 rows and 2 columns

torch.Size([2, 2])

In [14]:
#up until now they have all been gone over as tensors
#but its really like
#0D tensor = scalar, 1D tensor = vector, 2D tensor = matrix
#3D tensor = cube of numbers
#anything else would be a higher order tensor (4D, 5D, etc)
#like a hypercube

#this is a tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR
#tensors can represent almost anything
#the above tensor is a representation of sales numbers

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:

TENSOR.ndim

3

In [16]:
TENSOR.shape
#this is a bit confusing as it outputs ([1,3,3])
#but its a 3 dimenrsional tensor
#the dimensions go outter to inner


torch.Size([1, 3, 3])

In [17]:
"""
in conclusion, i have learned about the following:
scalar = single number and its dimension is 0
vector = a number with dirextion(like wind speed with direction) its dimension is 1
matrix = a 2d array of numbers its dimension is 2
tensor = a n-d array of numbers its dimension is n
"""
#ive learned i can use docstrings randomly for notes

'\nin conclusion, i have learned about the following:\nscalar = single number and its dimension is 0\nvector = a number with dirextion(like wind speed with direction) its dimension is 1\nmatrix = a 2d array of numbers its dimension is 2\ntensor = a n-d array of numbers its dimension is n\n'

In [21]:
#to create a tensor of random numbers
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.ndim, random_tensor.shape

(tensor([[0.1985, 0.8409, 0.1661, 0.8526],
         [0.1137, 0.9722, 0.3908, 0.7575],
         [0.6156, 0.9825, 0.5247, 0.7236]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

In [22]:
#this can be used to make random tensors in whatever size you want
#for example you could use torch.random(244,244,3)
#this wuold follow the common shape of an image
random_image_size_tensor = torch.rand(size=(244,244,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim
#hey copilot do i need to specify the size = key?
#copilot: no, you can just do torch.rand((244,244,3))
#why the double parenthesis?
#copilot: because it's a tuple
#so rand takes a tuple as an argument?
#copilot: yes
#will rand(244,244,3) work?
#copilot: no, it will throw an error


(torch.Size([244, 244, 3]), 3)

In [23]:
#to create a tensor full of zeros
zeros = torch.zeros(3,4)
zeros, zeros.dtype
#this can be used to create a tensor of any shape
#and the zeros can be accessed and filled with values

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [24]:
#to create a tensor full of ones
ones = torch.ones(3,4)
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [25]:
#to create a range of values
zero_to_ten = torch.arange(start=0, end=10, step=1)
#this is the pytorch arange (not arrange) function
#it is used to create a range of values with a set interval
#the start is the first value in the range
#the end is the last value in the range
#the step is the interval between each value in the range
#its important to remember it returns a tensor
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#hey copilot is like everything in torch just about tensors?
#copilot: yes, tensors are the main data structure in torch
#copilot: tensors are like numpy arrays, but they can also be used on a GPU to accelerate computing
#copilot: tensors are also optimized for automatic differentiation
#copilot: tensors are also the main data structure for neural networks in pytorch
#thanks copilot
#copilot: no problem
#copilot: I'm here to help
#is shape a very important thing in torch?
#copilot: yes, shape is very important in torch
"""so in the same way that i would need torch.zeros and torch.ones
to create a tensor of zeros and ones of any size from the jump
i would need torch.zeros_like and torch.ones_like
to create a tensor of ones or zeros in the same shape
as some other data im working with?"""
#copilot: yes, that's correct
#to create a tensor of zeros or ones in the same shape as some other data
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros 

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])